---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-0d2692b6acea72ee6
      keypair: AWS_AMI_NEW 

  tasks:
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "{{ my_access_key }}"
         aws_secret_key: "{{ my_secret_key }}"
         group: "launch-wizard-8"
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  
         count_tag:
            Name: "mithun-ansible-Demo"
         instance_tags:
            Name: "mithun-ansible-Demo"
         vpc_subnet_id: subnet-86ae20ca
         assign_public_ip: yes
      register: ec2
    
    - debug:
        msg: "{{ item['private_ip'] }}"
        with_items: "{{ ec2.instances }}"

    - name: Add all web instance IPs to host group
      add_host: 
        hostname: "{{ item.private_ip }}"
        groupname: webservers
        ansible_user: ec2-user 
      with_items: '{{ ec2.instances }} 
