---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-0d2692b6acea72ee6
      keypair: AWS_AMI_NEW

  tasks:
    - name: import new1.yml
      include: new.yml
